// templates/vue-app/src/App.vue
<template>
  <div class="app">
    <header class="app-header">
      <h1>FHEVM Vue Demo</h1>
      <div class="wallet-section">
        <button v-if="!isConnected" @click="connect" class="connect-btn">
          Connect Wallet
        </button>
        <div v-else class="connected-info">
          <span>{{ shortenAddress(address!) }}</span>
          <button @click="disconnect" class="disconnect-btn">Disconnect</button>
        </div>
      </div>
    </header>

    <main class="app-main">
      <div v-if="!isConnected" class="welcome-card">
        <h2>Welcome to FHEVM SDK</h2>
        <p>Connect your wallet to start using fully homomorphic encryption</p>
        <button @click="connect" class="primary-button">Connect Wallet</button>
      </div>

      <div v-else-if="isInitializing" class="loading">
        <div class="spinner"></div>
        <p>Initializing FHEVM client...</p>
      </div>

      <DemoSection
        v-else-if="fhevmClient"
        :fhevmClient="fhevmClient"
        :userAddress="address!"
      />

      <div v-else class="error-card">
        <p>Failed to initialize FHEVM client</p>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';
import { useAccount, useConnect, useDisconnect } from '@wagmi/vue';
import { injected } from 'wagmi/connectors';
import { createFHEVMClient, type FHEVMClient, VueAdapter } from '@fhevm/sdk';
import DemoSection from './components/DemoSection.vue';

const { address, isConnected } = useAccount();
const { connect: wagmiConnect } = useConnect();
const { disconnect: wagmiDisconnect } = useDisconnect();

const fhevmClient = ref<FHEVMClient | null>(null);
const isInitializing = ref(false);

function shortenAddress(addr: string): string {
  return `${addr.substring(0, 6)}...${addr.substring(addr.length - 4)}`;
}

function connect() {
  wagmiConnect({ connector: injected() });
}

function disconnect() {
  wagmiDisconnect();
}

async function initFHEVM() {
  if (!isConnected.value || fhevmClient.value) return;

  isInitializing.value = true;
  try {
    const adapter = new VueAdapter({
      chainId: Number(import.meta.env.VITE_CHAIN_ID || 11155111),
      provider: import.meta.env.VITE_RPC_URL || '',
      debug: true,
    });

    const client = adapter.getClient();
    fhevmClient.value = client;
  } catch (error) {
    console.error('Failed to initialize FHEVM client:', error);
  } finally {
    isInitializing.value = false;
  }
}

watch(isConnected, (connected) => {
  if (connected) {
    initFHEVM();
  } else {
    fhevmClient.value = null;
  }
});

onMounted(() => {
  if (isConnected.value) {
    initFHEVM();
  }
});
</script>

<style scoped>
.app {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  min-height: 100vh;
}

.app-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 3rem;
}

.app-header h1 {
  font-size: 2rem;
  margin: 0;
}

.wallet-section {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.connect-btn,
.disconnect-btn {
  padding: 0.75rem 1.5rem;
  border-radius: 8px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.3s;
}

.connect-btn {
  background: #42b883;
  color: white;
  border: none;
}

.connect-btn:hover {
  background: #33a06f;
}

.disconnect-btn {
  background: rgba(255, 255, 255, 0.1);
  color: white;
  border: 1px solid rgba(255, 255, 255, 0.2);
}

.disconnect-btn:hover {
  background: rgba(255, 255, 255, 0.15);
}

.connected-info {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.connected-info span {
  font-family: monospace;
  color: rgba(255, 255, 255, 0.9);
}

.app-main {
  display: flex;
  flex-direction: column;
  gap: 2rem;
}

.welcome-card,
.error-card {
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 12px;
  padding: 3rem;
  text-align: center;
}

.welcome-card h2 {
  margin-bottom: 1rem;
}

.welcome-card p {
  margin-bottom: 2rem;
  color: rgba(255, 255, 255, 0.7);
}

.primary-button {
  background: #42b883;
  color: white;
  border: none;
  padding: 0.75rem 2rem;
  font-size: 1rem;
  border-radius: 8px;
  cursor: pointer;
  transition: background 0.3s;
}

.primary-button:hover {
  background: #33a06f;
}

.loading {
  text-align: center;
  padding: 3rem;
}

.spinner {
  width: 50px;
  height: 50px;
  border: 4px solid rgba(255, 255, 255, 0.1);
  border-top-color: #42b883;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin: 0 auto 1rem;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

.error-card p {
  color: #ff6b6b;
}
</style>

// examples/nextjs-art-investment/app/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { useAccount, useConnect } from 'wagmi';
import { ConnectKitButton } from 'connectkit';
import { createFHEVMClient, type FHEVMClient } from '@fhevm/sdk';
import ArtworkList from '@/components/ArtworkList';
import InvestmentForm from '@/components/InvestmentForm';
import Portfolio from '@/components/Portfolio';

export default function Home() {
  const { address, isConnected } = useAccount();
  const [fhevmClient, setFhevmClient] = useState<FHEVMClient | null>(null);
  const [isInitializing, setIsInitializing] = useState(false);

  useEffect(() => {
    async function initFHEVM() {
      if (!isConnected || fhevmClient) return;

      setIsInitializing(true);
      try {
        const client = await createFHEVMClient({
          chainId: Number(process.env.NEXT_PUBLIC_CHAIN_ID || 11155111),
          provider: process.env.NEXT_PUBLIC_RPC_URL || '',
          debug: true,
        });
        setFhevmClient(client);
      } catch (error) {
        console.error('Failed to initialize FHEVM client:', error);
      } finally {
        setIsInitializing(false);
      }
    }

    initFHEVM();
  }, [isConnected, fhevmClient]);

  return (
    <main className="min-h-screen bg-gradient-to-br from-purple-50 to-blue-50 dark:from-gray-900 dark:to-gray-800">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <header className="flex justify-between items-center mb-12">
          <div>
            <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-2">
              Private Art Investment
            </h1>
            <p className="text-gray-600 dark:text-gray-300">
              Invest in fine art with complete privacy using FHE encryption
            </p>
          </div>
          <ConnectKitButton />
        </header>

        {/* Content */}
        {!isConnected ? (
          <div className="text-center py-20">
            <div className="max-w-md mx-auto bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8">
              <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">
                Welcome to Private Art Investment
              </h2>
              <p className="text-gray-600 dark:text-gray-300 mb-6">
                Connect your wallet to start investing in fine art with complete privacy protection.
              </p>
              <ConnectKitButton />
            </div>
          </div>
        ) : isInitializing ? (
          <div className="text-center py-20">
            <div className="inline-block animate-spin rounded-full h-12 w-12 border-4 border-purple-500 border-t-transparent"></div>
            <p className="mt-4 text-gray-600 dark:text-gray-300">
              Initializing FHEVM client...
            </p>
          </div>
        ) : fhevmClient ? (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Left Column - Artwork List */}
            <div className="lg:col-span-2">
              <ArtworkList
                fhevmClient={fhevmClient}
                userAddress={address!}
              />
            </div>

            {/* Right Column - Investment & Portfolio */}
            <div className="space-y-6">
              <InvestmentForm
                fhevmClient={fhevmClient}
                userAddress={address!}
              />
              <Portfolio
                fhevmClient={fhevmClient}
                userAddress={address!}
              />
            </div>
          </div>
        ) : (
          <div className="text-center py-20">
            <p className="text-red-600 dark:text-red-400">
              Failed to initialize FHEVM client. Please refresh and try again.
            </p>
          </div>
        )}
      </div>
    </main>
  );
}
